version: '2'
services:
  inthehood.dog.mariadb:
    container_name: inthehood.dog.mariadb
    image: 'inthehood.dog.git.pull/mariadb:10.3'
    build: './mariadb/10.3'
    restart: always
    volumes:
      - 'inthehood-dog-cc-mariadb_data:/bitnami'
    ports:
        - '3350:3350'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  inthehood.dog:
    container_name: inthehood.dog.wordpress
    image: 'bitnami/wordpress:5'
    restart: always
    ports:
        - '3351:3351'
    volumes:
      - 'inthehood-dog-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './bitnami/wordpress/wp-content:/bitnami/wordpress/wp-content'
    depends_on:
      - inthehood.dog.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=inthehood.dog.mariadb
      - MARIADB_PORT_NUMBER=3350
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=inthehood.dog
      - LETSENCRYPT_HOST=inthehood.dog
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  inthehood-dog-cc-mariadb_data:
    driver: local
  inthehood-dog-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

